"""create exams table

Revision ID: 0a7dd6a35345
Revises: d3df7dec2228
Create Date: 2026-05-04 01:37:17.906074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7dd6a35345'
down_revision: Union[str, None] = 'd3df7dec2228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=80), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinical_indication', sa.Text(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('ai_analysis_status', sa.String(length=50), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=180), nullable=True),
    sa.Column('file_mime_type', sa.String(length=100), nullable=True),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_clinic_id'), 'exams', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_exams_doctor_id'), 'exams', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_exams_exam_type'), 'exams', ['exam_type'], unique=False)
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.create_index(op.f('ix_exams_patient_id'), 'exams', ['patient_id'], unique=False)
    op.create_index(op.f('ix_exams_status_id'), 'exams', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_status_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_patient_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_type'), table_name='exams')
    op.drop_index(op.f('ix_exams_doctor_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_clinic_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
