"""create clinics table

Revision ID: 4c7d08d3d8c1
Revises: eb26f6fa97a1
Create Date: 2026-05-05 22:52:34.453808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7d08d3d8c1'
down_revision: Union[str, None] = 'eb26f6fa97a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile_phone', sa.String(length=20), nullable=True),
    sa.Column('zip_code', sa.String(length=8), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj', name='uq_clinics_cnpj'),
    sa.UniqueConstraint('email', name='uq_clinics_email')
    )
    op.create_index(op.f('ix_clinics_cnpj'), 'clinics', ['cnpj'], unique=False)
    op.create_index(op.f('ix_clinics_email'), 'clinics', ['email'], unique=False)
    op.create_index(op.f('ix_clinics_id'), 'clinics', ['id'], unique=False)
    op.create_index(op.f('ix_clinics_name'), 'clinics', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinics_name'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_id'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_email'), table_name='clinics')
    op.drop_index(op.f('ix_clinics_cnpj'), table_name='clinics')
    op.drop_table('clinics')
    # ### end Alembic commands ###
